### PR TITLE
Setup changes

### PR DESCRIPTION
**Pull request by RobertRosca**
Main change is that I added a `pyproject.toml` file which notes that numpy is a build-time dependency, and installs it before the setup phase begins.

Changes:
- Added `pyproject.toml`
  - Introduced in [pep 517](https://www.python.org/dev/peps/pep-0517/), lets you specify build time dependencies
  - Has `numpy` as a build time dependency so that it is available to compile the fortran code during setup
- Refactored `setup.py` a bit
  - Numpy should always be available now, so the checks are not necessary anymore
  - That means you can call setup directly instead of having to pass the easy to edit `metadata` dictionary to it as an argument
- New additions to gitignore
  - Most are for me :stuck_out_tongue: 
  - Added `/Xana/XpcsAna/fecorrt3m.cpython*.so**` to ignore all compiled fortran
  - Added `/pip-wheel-metadata/` to ignore pep 517 generated files
- Enabled warning in `Xana/XpcsAna/eventcorrelator3.py` when `fecorrt3m` could not be imported (as it should always be importable now)
- Deleted `Xana/XpcsAna/fecorrt3m.cpython-37m-darwin.so`, is that okay?

### CODE REVIEW

**Comment by reiserm** [comment]
There seems to be an issue with compiling the Fortran routines (see below). It could be that there is a local issue with the available Fortran compiler. I think it is gfortran on Linux or gcc. Do you think we could check for the availability of the compiler? I am not sure if the error is really related to this but I think it would be good to print a message anyway when the installation fails due to a missing compiler.

    ERROR: Command errored out with exit status 1:
     command: /Users/reiserm/anaconda3/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/reiserm/Xana/setup.py'"'"'; __file__='"'"'/Users/reiserm/Xana/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/reiserm/Xana/
    Complete output (14 lines):
    running develop
    running egg_info
    writing Xana.egg-info/PKG-INFO
    writing dependency_links to Xana.egg-info/dependency_links.txt
    writing requirements to Xana.egg-info/requires.txt
    writing top-level names to Xana.egg-info/top_level.txt
    reading manifest file 'Xana.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Xana.egg-info/SOURCES.txt'
    running build_ext
    building 'Xana.XpcsAna.fecorrt3m' extension
    C compiler: x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/reiserm/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/reiserm/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/reiserm/anaconda3/include

    error: unknown file type '.f90' (from 'Xana/XpcsAna/fecorrt3m.f90')

**Comment by reiserm** [comment]
There is still a compiler issue. I guess you are testing this on Linux, right? 

  Running setup.py develop for Xana
    ERROR: Command errored out with exit status 1:
     command: /Users/reiserm/anaconda3/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/reiserm/Xana/setup.py'"'"'; __file__='"'"'/Users/reiserm/Xana/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/reiserm/Xana/
    Complete output (68 lines):
    running develop
    running build_scripts
    running egg_info
    running build_src
    build_src
    building extension "Xana.XpcsAna.fecorrt3m" sources
    f2py options: ['--verbose']
      adding 'build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.c' to sources.
      adding 'build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna' to include_dirs.
    build_src: building npy-pkg config files
    writing Xana.egg-info/PKG-INFO
    writing dependency_links to Xana.egg-info/dependency_links.txt
    writing requirements to Xana.egg-info/requires.txt
    writing top-level names to Xana.egg-info/top_level.txt
    reading manifest file 'Xana.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Xana.egg-info/SOURCES.txt'
    running build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
    customize Gnu95FCompiler
    Found executable /usr/local/bin/gfortran
    Found executable /Users/reiserm/anaconda3/bin/x86_64-apple-darwin13.4.0-ld
    Found executable /Users/reiserm/anaconda3/bin/x86_64-apple-darwin13.4.0-ar
    Found executable /Users/reiserm/anaconda3/bin/x86_64-apple-darwin13.4.0-ranlib
    customize Gnu95FCompiler
    customize Gnu95FCompiler using build_ext
    building 'Xana.XpcsAna.fecorrt3m' extension
    compiling C sources
    C compiler: x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/reiserm/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/reiserm/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/reiserm/anaconda3/include

    compile options: '-Ibuild/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna -I/private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include -I/Users/reiserm/anaconda3/include/python3.7m -I/Users/reiserm/anaconda3/include/python3.7m -c'
    x86_64-apple-darwin13.4.0-clang: build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.c
    x86_64-apple-darwin13.4.0-clang: build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.c
    clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
    clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
    In file included from build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.c:16:
    In file included from build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.h:13:
    In file included from /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
    /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    In file included from build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.c:2:
    In file included from build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.h:13:
    In file included from /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
    /private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.c:109:12: warning: unused function 'f2py_size' [-Wunused-function]
    static int f2py_size(PyArrayObject* var, ...)
               ^
    2 warnings generated.
    1 warning generated.
    compiling Fortran sources
    Fortran f77 compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
    Fortran f90 compiler: /usr/local/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
    Fortran fix compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
    compile options: '-Ibuild/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna -I/private/var/folders/rm/7p32_txj0jn04xcsngj64ps00000gn/T/pip-build-env-78xojesb/overlay/lib/python3.7/site-packages/numpy/core/include -I/Users/reiserm/anaconda3/include/python3.7m -I/Users/reiserm/anaconda3/include/python3.7m -c'
    gfortran:f90: Xana/XpcsAna/fecorrt3m.f90
    /usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.o build/temp.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3m.o -L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0 -L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/../../.. -L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/../../.. -lgfortran -o Xana/XpcsAna/fecorrt3m.cpython-37m-darwin.so
    ld: could not parse object file build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.o: 'Unknown attribute kind (61) (Producer: 'LLVM10.0.0' Reader: 'LLVM APPLE_1_1103.0.32.62_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.62)' file 'build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.o'
    collect2: error: ld returned 1 exit status
    error: Command "/usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3mmodule.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fortranobject.o build/temp.macosx-10.9-x86_64-3.7/Xana/XpcsAna/fecorrt3m.o -L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0 -L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/../../.. -L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/../../.. -lgfortran -o Xana/XpcsAna/fecorrt3m.cpython-37m-darwin.so" failed with exit status 1

**Comment by RobertRosca** [comment]
Hmm, interesting, I wanted to do this in a different PR to keep things vaguely organised, but I'll set up a CI test on ubuntu and macos which just installs the package to see where the error occurs.

The user will still need to have a fortran compiler installed themselves for this to work (which I assume most people installing any kind of scientific software would already have), but past that the setup should work fine, granted I have no experience on Mac so I might be missing something.

**Comment by reiserm** [comment]
I think that is a good idea (the test I mean).

Do you think we need to specify the required numpy version? I know that on macos it can be a bit tedious to use f2py. I wrote in the installation instruction that you might have to `unset SHELL` and `unset LDFLAGS` to get it working, but this does not help me here.

**Comment by RobertRosca** [comment]
OK so I set up the tests on my fork so that I could include them on the master branch as well.

For master it works (well, fails) as expected: successfully installs the package without the `build_ext` step, which means the fortran isn't compiled, then it fails the import test: https://github.com/RobertRosca/Xana/runs/830101884

For my branch with the modified setup script it correctly installs numpy as a build dependency, then run with the `build_ext` step*, and passes the import test for both ubuntu and macos as shown in the tests: https://github.com/reiserm/Xana/pull/3/checks?check_run_id=830190724

It's not too clear to me why it would fail on your machine, might be a dependency issue or something. Could you try:

```
git clone --branch setup-changes git@github.com:reiserm/Xana.git
cd Xana
python -m venv .venv
source .venv/bin/activate
pip install -e .
```

I assume the steps for creating and activating a venv are the same on mac but I'm not sure. If the install works correctly then do `python -c "import Xana.XpcsAna.fecorrt3m"` to see if it can actually import the module.

*(for some reason the install needs to be done with `pip install -e` otherwise the fortran module isn't made available even though it is compiled, I'll look into fixing this now)

**Comment by reiserm** [comment]
OK this seems to work, also importing the Fortran module after installation. Great 👍 

I think this step could be quite frustrating for other users. Is there some way of checking for dependency issues? When the installation failed I was using my standard anaconda environment but from the f2py error it was not really clear what the issue was.

**Comment by RobertRosca** [comment]
I can add minimum version numbers for the dependency, but without knowing what version is actually needed it'll be a bit of an arbitrary choice.

Also as you're using an anaconda environment that makes finding out the versions and checking the correct packages are installed more difficult. It's not recommended to mix pip-installed packages and conda packages in a single environment as it can cause a lot of dependency issues and conflicts.

Could you activate the environment and run `pip list` as well as `conda list` and copy/paste the output to both here? I'll try to figure out where the incompatibility comes from.

**Comment by reiserm** [comment]
I wrote the packages to the attached files.

[conda_packages.txt](https://github.com/reiserm/Xana/files/4866522/conda_packages.txt)
[pip_packages.txt](https://github.com/reiserm/Xana/files/4866523/pip_packages.txt)

I am using anaconda mainly for convenience. However, when I work on Xana, I usually installed it with pip and the `-e` flag to see the effect of code changes directly in, e.g., a notebook. Maybe there is a more clever way of doing this. Would you avoid anaconda completely?

**Comment by RobertRosca** [comment]
Looked through the requirements and couldn't find any specific versions that would cause that problem, so I just added some basic version requirements:

```python
    install_requires=[
        'cbf>=1.0',
        'corner>=2.0',
        'emcee>=3.0',
        'h5py>=2.0',
        'ipywidgets',
        'lmfit>=1.0',
        'matplotlib',
        'numpy>=1.19',
        'pandas>=1.0',
        'pyfai>=0.19',
        'seaborn'
    ],
```

Which will be fine unless there are version conflicts which, realistically, there shouldn't be many of. The only case where an older version than those specified above is needed would be if a major feature was changed in one of those packages which breaks backwards compatibility, but as those are mostly all major python packages they don't break backwards compatibility often so I don't think this should be an issue.

> I am using anaconda mainly for convenience. However, when I work on Xana, I usually installed it with pip and the -e flag to see the effect of code changes directly in, e.g., a notebook. Maybe there is a more clever way of doing this. Would you avoid anaconda completely?

Personally I strongly dislike anaconda. The interoperability between anaconda and pip is not good and can be very fragile, leading to a lot of issues which [Continuum is aware of](https://www.anaconda.com/using-pip-in-a-conda-environment/).

The only reason to use conda is if you have some complex requirement that cannot be installed from pypi and must be installed via conda, which (from what I've heard at least, since I'm too young to have experienced it myself :stuck_out_tongue: ) used to happen with packages a few years ago when pypi/pip/setuptools weren't flexible enough. But now the build tools in python are good enough on their own to handle this so conda just adds in another layer of complexity where things can go wrong.

I'd recommend using environments in the way I asked you to test the install steps before. Native python venv's are more than enough for this use case. Personally for this kind of thing I do:

```
git clone some-repository-I-want-to-work-on
cd repo
python -m venv .venv
source .venv/bin/activate
pip install -e .
pip install jupyterlab
jupyter lab
```

Which is very useful as then the native `python` kernel is using your activated environment, so you don't have to juggle multiple kernels around or change the kernel for your notebook. Alternatively you can run `python -m ipykernel install --user --name "repo"` to create a kernel for that environment, which you can then use for any notebooks, this is useful if you want to use max-jhub.

**Pull request merged**
